---
- name: Load file to sharepoint test
  hosts: localhost
  connection: local
  gather_facts: false

#    sharepoint_directory: "{{ sharepoint_dir | default('/sites/IT-Team-ORE/Network Documentation/009 ENS-IA Audits/Internal Audit & Remediation/Operation Data Reports/BGP Session State') }}"
  #  client_id: "xxxxxx"
  #  client_secret: "xxxxxxx"

  tasks:
    - name: Gather the file from sftp 11
      ansible.builtin.get_url:
         url: sftp.access.redhat.com/{{ report_dir }}/{{ report_name }}
         dest: /home/cloud-user/
         username: rhn-support-kdwyer
         password: password123
      delegate_to: localhost
