---
- name: This play is to make a key and cert
  become: true
  hosts: all
  tasks:
    - name: Make the directory path
      ansible.builtin.file:
        path: /etc/pki/nginx/private
        state: directory
        mode: '0755'
    - name: Ensure private key is present
      community.crypto.openssl_privatekey:
        path: /etc/pki/nginx/private/server.key
        size: 2048
        mode: "0600"
        type: RSA
    - name: Ensure self-signed cert is present
      community.crypto.x509_certificate:
        path: /etc/pki/nginx/server.crt
        privatekey_path: /etc/pki/nginx/privateredis-server.key
        provider: selfsigned
        selfsigned_not_after: "+3650d" # this is the default
        mode: "0644"
